name: Feature request
description: Propose an improvement or new capability for SIGNIA.
title: "[Feature]: "
labels:
  - enhancement
  - needs-triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature.

        **Guidelines**
        - Keep the request focused: one feature per issue.
        - Describe the problem first, then the solution.
        - If this impacts determinism or schema versions, call that out explicitly.
        - Do not include secrets.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area does this feature affect?
      multiple: true
      options:
        - Core compiler pipeline (Parse / Infer / Compile / Verify)
        - Determinism / canonicalization / hashing
        - Schema format (schemas/v1)
        - Proof format (Merkle/proofs)
        - Plugins system (contract / sandboxing)
        - Built-in plugin: GitHub repo
        - Built-in plugin: Dataset
        - Built-in plugin: Specs / Markdown
        - Built-in plugin: OpenAPI
        - Built-in plugin: Workflow
        - Built-in plugin: Config
        - CLI (crates/signia-cli)
        - API service (crates/signia-api)
        - Solana registry program (programs/signia-registry)
        - SDK: TypeScript (sdk/ts)
        - SDK: Python (sdk/python)
        - Console (console/web)
        - Interface module (console/interface)
        - Docs
        - CI / Release / Tooling
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve? Who is affected and why does it matter?
      placeholder: |
        Describe the pain point.
        Example:
        - Today SIGNIA cannot ...
        - This blocks ...
        - Users/workflows impacted: ...
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: What outcomes should this feature achieve? Keep it measurable when possible.
      placeholder: |
        - Goal 1:
        - Goal 2:
        - Goal 3:
    validations:
      required: true

  - type: textarea
    id: non_goals
    attributes:
      label: Non-goals
      description: What is explicitly out of scope for this request?
      placeholder: |
        - Not in scope:
        - Not in scope:
    validations:
      required: false

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your proposed approach. Include design details, constraints, and API/CLI shape if relevant.
      placeholder: |
        Provide a concrete proposal:
        - UX / CLI commands:
        - API endpoints:
        - Data model changes:
        - Plugin changes:
        - On-chain changes:
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches did you consider? Why are they worse?
      placeholder: |
        - Alternative 1:
        - Alternative 2:
    validations:
      required: false

  - type: dropdown
    id: breaking_changes
    attributes:
      label: Breaking change potential
      description: Could this require a schema version bump or break existing integrations?
      multiple: false
      options:
        - Unknown
        - No
        - Yes (likely)
        - Yes (certain)
    validations:
      required: true

  - type: textarea
    id: schema_impact
    attributes:
      label: Schema/proof impact (if any)
      description: If this changes schemas, manifests, proofs, or hashing/canonicalization, describe what would change.
      placeholder: |
        - Schema fields to add/remove/change:
        - Proof format impact:
        - Hashing/canonicalization impact:
        - Backward compatibility strategy:
    validations:
      required: false

  - type: dropdown
    id: determinism_impact
    attributes:
      label: Determinism impact
      description: Does this feature affect deterministic output (same input → same output)?
      multiple: false
      options:
        - Unknown
        - No
        - Yes (needs deterministic rules)
    validations:
      required: true

  - type: textarea
    id: determinism_notes
    attributes:
      label: Determinism notes (if applicable)
      description: If determinism is impacted, describe how deterministic behavior should be defined and tested.
      placeholder: |
        - Inputs that must be canonicalized:
        - Ordering/stability rules:
        - Hash domain separation changes:
        - Golden fixture strategy:
    validations:
      required: false

  - type: dropdown
    id: onchain_impact
    attributes:
      label: On-chain impact
      description: Does this require changes to the Solana registry program?
      multiple: false
      options:
        - Unknown
        - No
        - Yes (program change required)
        - Yes (new instruction/account required)
    validations:
      required: true

  - type: textarea
    id: api_cli_shape
    attributes:
      label: Proposed API/CLI shape (optional)
      description: Suggest command flags, endpoint paths, request/response shapes, or SDK interfaces.
      render: text
      placeholder: |
        CLI:
        - signia <cmd> --flag ...
        API:
        - POST /v1/...
        - GET /v1/...
        SDK:
        - client.method(...)
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Risks / trade-offs
      description: Performance, security, complexity, determinism, backward compatibility, or user experience risks.
      placeholder: |
        - Risk:
        - Mitigation:
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (requester estimate)
      description: How urgent/important is this to you?
      multiple: false
      options:
        - P0 (critical blocker)
        - P1 (high)
        - P2 (medium)
        - P3 (low)
    validations:
      required: true

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution interest
      description: Are you willing to contribute a PR if the approach is agreed?
      multiple: false
      options:
        - Yes, I can implement
        - Yes, I can help
        - Maybe
        - No
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Link to similar systems, specs, repos, issues, or docs that support the request.
      placeholder: |
        - Link:
        - Link:
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Confirm the following before submitting.
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: This request is focused on a single feature.
          required: true
        - label: I described the problem clearly and provided a concrete proposal.
          required: true
        - label: I removed secrets and private information from examples.
          required: true
