name: Question
description: Ask a technical question about SIGNIA usage, design, or deployment.
title: "[Question]: "
labels:
  - question
  - needs-triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this form to ask technical questions about SIGNIA.

        **Before you submit**
        - Check the documentation and existing issues.
        - Provide enough context to reproduce or reason about the question.
        - Do not include secrets (API keys, private repo URLs, wallet keys, tokens).

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: What is your question primarily about?
      multiple: true
      options:
        - Getting started / Installation
        - CLI usage
        - Compiler pipeline (Parse / Infer / Compile / Verify)
        - Determinism and canonicalization
        - Schemas / Manifests / Proofs
        - Plugins (built-in or custom)
        - API service
        - Solana registry program
        - Publishing to Solana (localnet/devnet/testnet/mainnet-beta)
        - SDK: TypeScript
        - SDK: Python
        - Console (web)
        - Interface module
        - Performance / scaling
        - Security / trust model
        - CI / Release
        - Docs
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question clearly and concisely.
      placeholder: |
        What are you trying to do?
        What is unclear or not working as expected?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide relevant background so maintainers can answer accurately.
      placeholder: |
        - Use case:
        - Input type (repo/dataset/spec/api/workflow/config):
        - Expected outcome:
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version(s)
      description: Provide the versions you are using (release tag or commit SHA).
      placeholder: "e.g. v0.1.0 or commit 1a2b3c4"
    validations:
      required: false

  - type: dropdown
    id: environment_scope
    attributes:
      label: Environment scope
      description: Where does this question apply?
      multiple: false
      options:
        - Local development
        - CI environment
        - Containerized (Docker)
        - Solana localnet
        - Solana devnet
        - Solana testnet
        - Solana mainnet-beta
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: commands
    attributes:
      label: Commands or configuration used
      description: Paste relevant commands, configs, or snippets. Remove secrets.
      render: shell
      placeholder: |
        ```bash
        signia compile ...
        signia verify ...
        signia publish ...
        ```
    validations:
      required: false

  - type: textarea
    id: outputs
    attributes:
      label: Output or logs
      description: Paste any output or logs that help explain the question.
      render: shell
      placeholder: |
        ```text
        ...
        ```
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected understanding or outcome
      description: What answer or behavior are you expecting?
      placeholder: |
        Describe the expected behavior or clarification you are seeking.
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to docs, issues, specs, or code that are relevant.
      placeholder: |
        - Link:
        - Link:
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Confirm the following before submitting.
      options:
        - label: I searched existing issues and documentation.
          required: true
        - label: I provided sufficient context for someone else to understand the question.
          required: true
        - label: I removed secrets and private information from all content.
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional notes
      description: Any extra details that might help answer the question.
      placeholder: "Add any additional notes here."
    validations:
      required: false
